module MetaTags
  class Configuration
    type html_tag_key = String | Symbol
    type html_tag_value = Hash[html_tag_key, html_tag_value] | html_tag_content
    type html_tag_content = String? | Symbol | (_Stringish & Object)


    attr_accessor title_limit: Integer?
    attr_accessor truncate_site_title_first: bool
    attr_accessor truncate_on_natural_separator: String?|Regexp
    attr_accessor title_tag_attributes: Hash[html_tag_key, html_tag_value]?
    attr_accessor description_limit: Integer
    attr_accessor keywords_limit: Integer
    attr_accessor keywords_separator: String
    attr_accessor keywords_lowercase: bool
    attr_accessor open_meta_tags: bool
    attr_accessor minify_output: bool
    attr_reader property_tags: Array[String | Symbol]
    attr_accessor skip_canonical_links_on_noindex: bool

    def initialize: () -> void
    def default_property_tags: () -> Array[String | Symbol]
    def open_meta_tags?: () -> bool
    def reset_defaults!: () -> void
  end
end
