module MetaTags
  module ControllerHelper : _ActionControllerBase
    def render: (*untyped args) { () -> untyped } -> untyped

    def set_meta_tags: (ViewHelper::meta_tags | (_MetaTagish & Object) meta_tags) -> void

    def meta_tags: () -> MetaTagsCollection
  end
end
