module MetaTags
  module ViewHelper : Module, _ActionViewBase
    @meta_tags: MetaTagsCollection?

    type stringish = String | (_Stringish & Object)
    type robots_value = bool | String | Array[String]

    def meta_tags: () -> MetaTagsCollection

    def set_meta_tags: (?meta_tags | (_MetaTagish & Object) meta_tags) -> void

    def title: (?(stringish | Array[stringish]) title, ?::String? headline) -> String

    def keywords: (TextNormalizer::keywords keywords) -> TextNormalizer::keywords

    def description: (TextNormalizer::keyword description) -> TextNormalizer::keyword

    def noindex: (?robots_value noindex) -> robots_value

    def nofollow: (?robots_value nofollow) -> robots_value

    def refresh: (TextNormalizer::keyword | Integer? refresh) -> (TextNormalizer::keyword | Integer?)

    def display_meta_tags: (?meta_tags defaults) -> String

    def display_title: (?meta_tags defaults) -> String
  end
end
