name: Dependabot

on:
  pull_request:
    types: [labeled]

concurrency:
  group: dependabot-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  build:
    if: github.event.label.name == 'bundler' && github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - "3.3"

    name: Appraisal - Ruby ${{ matrix.ruby-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Update Appraisal gemfiles
        run: |
          bundle exec appraisal update
      - name: Upload Appraisal lockfiles
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dependabot-appraisal-lockfiles
          path: gemfiles/*.lock
          if-no-files-found: error
          retention-days: 1
