name: scorecards

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analysis:
    name: scorecards
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required by Scorecard to inspect repository contents.
      security-events: write # Required to upload Scorecard SARIF results.
      id-token: write # Required by Scorecard to publish signed results.
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@0c0c5dc2f136b98cb0537075ccfa21f94cd9a63e # codeql-bundle-v2.24.3
        with:
          sarif_file: results.sarif
